---
- name: install openssh
  apt:
    name: openssh-server
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: drop in sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh
